### ISSUE TITLE
C#8 Nullable References

### ISSUE THREAD

**Issue by SeriousM** [cezarypiatek/CSharpExtensions#2]
Hi! Your article was very nice, ty for that.
We're using the new feature from c# to annotate nullable reference types with poco classes.
Since the new feature requires properties to be initialized if not mentioned in a constructor we came up with this pattern:

```cs
public class ModelPoco
{
  public User CurrentUser { get; set; } = default!;
}
```

This way the adaption on legacy code is quite simple by just appending ` = default!;" to each property.

Could your extension help to avoid this additional code?

Best, Bernhard

**Comment by cezarypiatek** [comment]
If you are going to use `[InitOnly]` or `[InitRequired]` with non-nullable fields then it's perfectly fine to disable `CS8618` rule. You can do that via .editorconfig with the following entry
```
[*.cs]
#CS8618: Non-nullable property ‘PropertyName’ is uninitialized.
dotnet_diagnostic.CS8618.severity = none
```

**Comment by SeriousM** [comment]
Hmm, well, our codebase is quite large and the disabling the rule CS8618 would be counter-intuitive. Could your analyser disable this rule just for types/members that have your attribute applied?

**Comment by cezarypiatek** [comment]
It looks like Roslyn support such scenario thanks to `DiagnosticSuppressor`  https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.diagnostics.diagnosticsuppressor?view=roslyn-dotnet

I will try to implement it. Thanks for reporting this suggestion.

**Comment by SeriousM** [comment]
Thank you for investigating it!

**Comment by cezarypiatek** [comment]
I have a working POC. I will try to finish it and publish it today afternoon.

**Comment by cezarypiatek** [comment]
@SeriousM I've just released version `2.1.31` with the requested feature. Please let me know if it works as expected.

**Comment by cezarypiatek** [comment]
@SeriousM I've introduced another attribute `[assembly:InitRequiredForNotNull]` which works on assembly level. Everything described on my blog https://cezarypiatek.github.io/post/better-non-nullable-handling/

**Comment by stijnherreman** [comment]
For anyone trying out this library with VS Code: `DiagnosticSuppressor` is not yet supported by OmniSharp (https://github.com/OmniSharp/omnisharp-roslyn/issues/1711) so the Problems panel will still show the warnings.
